apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: san
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  provisioningType: "thin"
reclaimPolicy: Retain
allowVolumeExpansion: true